# Generated by Django 6.0.6 on 2026-06-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('public_hospital', 'Public Hospital'), ('private_hospital', 'Private Hospital'), ('clinic', 'Clinic'), ('home_care', 'Home Care Provider'), ('frail_care', 'Frail Care Facility'), ('other', 'Other')], max_length=30)),
                ('province', models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('EC', 'Eastern Cape'), ('FS', 'Free State'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West')], max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursing_category', models.CharField(max_length=20)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('number_of_nurses', models.PositiveIntegerField(default=1)),
                ('shift_type', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate (within 24hrs)'), ('urgent', 'Urgent (within 48hrs)'), ('planned', 'Planned (more than 48hrs)')], default='planned', max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requests', to='employers.employerprofile')),
            ],
        ),
    ]
