# Generated by Django 6.0.6 on 2026-06-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('sanc_number', models.CharField(max_length=50, unique=True)),
                ('nursing_category', models.CharField(choices=[('registered', 'Registered Nurse'), ('enrolled', 'Enrolled Nurse'), ('auxiliary', 'Auxiliary Nurse'), ('specialist', 'Specialist Nurse'), ('midwife', 'Midwife')], max_length=20)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('province', models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('EC', 'Eastern Cape'), ('FS', 'Free State'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West')], max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NurseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sanc_certificate', 'SANC Certificate'), ('id_document', 'ID Document'), ('cv', 'Curriculum Vitae'), ('qualification', 'Qualification Certificate'), ('reference', 'Reference Letter'), ('criminal_clearance', 'Criminal Clearance')], max_length=30)),
                ('file', models.FileField(upload_to='nurse_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nurses.nurseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NurseAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('both', 'Day & Night')], max_length=10)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nurses.nurseprofile')),
            ],
            options={
                'unique_together': {('nurse', 'day', 'shift')},
            },
        ),
    ]
