# Generated by Django 6.0.6 on 2026-07-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('filled', 'Filled'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
